import type { LucideIcon } from "lucide-react";
import {
  AlertTriangle,
  ArrowDown,
  ArrowLeft,
  ArrowLeftRight,
  ArrowRight,
  ArrowUp,
  ArrowUpRight,
  Ban,
  BarChart3,
  BarChartBig,
  Bell,
  BookOpen,
  Boxes,
  Building,
  Building2,
  Calculator,
  CalendarClock,
  Check,
  CheckCheck,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsUpDown,
  CircleAlert,
  ClipboardCheck,
  ClipboardPaste,
  Copy,
  Download,
  ExternalLink,
  Factory,
  Eye,
  EyeOff,
  FileClock,
  FilePlus2,
  Files,
  FileSpreadsheet,
  FileText,
  Filter,
  HelpCircle,
  Info,
  KeyRound,
  Landmark,
  LayoutDashboard,
  List,
  ListChecks,
  Loader2,
  Lock,
  LockOpen,
  Mail,
  Maximize2,
  Minimize2,
  Minus,
  Moon,
  PackagePlus,
  Palette,
  PanelLeftClose,
  PanelLeftOpen,
  Paperclip,
  Pencil,
  Plus,
  Power,
  Printer,
  ReceiptText,
  RefreshCw,
  RotateCcw,
  Save,
  Scale,
  Search,
  Send,
  Settings,
  Shield,
  ShoppingCart,
  SlidersHorizontal,
  Sparkles,
  Square,
  Sun,
  Trash2,
  TrendingDown,
  TrendingUp,
  Undo2,
  Volume2,
  VolumeX,
  Upload,
  User,
  WalletCards,
  Warehouse,
  X,
} from "lucide-react";

/**
 * Semantic registry: page-ууд Lucide-ийн дүрсний нэр биш, бизнесийн утга
 * (`add`, `inventory`, `period`, `warning`) сонгоно. Ингэснээр glyph-ийг энэ
 * файлаас нэг удаа солиход бүх migrated callsite дагана.
 */
export const ICONS = {
  // Actions
  add: Plus,
  addDocument: FilePlus2,
  approve: Check,
  approveAll: CheckCheck,
  attach: Paperclip,
  cancel: Ban,
  close: X,
  copy: Copy,
  delete: Trash2,
  download: Download,
  duplicate: Files,
  edit: Pencil,
  filter: Filter,
  maximize: Maximize2,
  minimize: Minimize2,
  openExternal: ExternalLink,
  openDetail: ArrowUpRight,
  power: Power,
  print: Printer,
  refresh: RefreshCw,
  soundOn: Volume2,
  soundOff: VolumeX,
  reset: RotateCcw,
  save: Save,
  search: Search,
  send: Send,
  stop: Square,
  undo: Undo2,
  upload: Upload,

  // Navigation and disclosure
  arrowDown: ArrowDown,
  arrowLeft: ArrowLeft,
  arrowRight: ArrowRight,
  arrowUp: ArrowUp,
  chevronDown: ChevronDown,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  collapseSidebar: PanelLeftClose,
  expandSidebar: PanelLeftOpen,
  select: ChevronsUpDown,

  // State and feedback
  bell: Bell,
  error: CircleAlert,
  help: HelpCircle,
  info: Info,
  loading: Loader2,
  locked: Lock,
  pending: FileClock,
  success: CheckCircle2,
  unlocked: LockOpen,
  warning: AlertTriangle,

  // Visibility and data tools
  hide: EyeOff,
  list: List,
  checklist: ListChecks,
  show: Eye,
  tune: SlidersHorizontal,

  // Product/module concepts
  ai: Sparkles,
  bank: Landmark,
  cash: WalletCards,
  company: Building2,
  costing: Calculator,
  counting: ClipboardCheck,
  dashboard: LayoutDashboard,
  depreciation: TrendingDown,
  document: ReceiptText,
  file: FileText,
  fixedAsset: Building,
  generalLedger: BookOpen,
  inventory: Boxes,
  journal: List,
  key: KeyRound,
  mail: Mail,
  movement: ArrowLeftRight,
  packageReceipt: PackagePlus,
  period: CalendarClock,
  production: Factory,
  purchaseOrder: ShoppingCart,
  reconciliation: Scale,
  report: BarChart3,
  reportDetailed: BarChartBig,
  settings: Settings,
  shield: Shield,
  spreadsheet: FileSpreadsheet,
  theme: Palette,
  trendDown: TrendingDown,
  trendUp: TrendingUp,
  user: User,
  warehouse: Warehouse,

  // Import and clipboard
  paste: ClipboardPaste,

  // Theme
  darkMode: Moon,
  lightMode: Sun,

  // Small structural marks
  minus: Minus,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;

export type IconCategory =
  | "action"
  | "navigation"
  | "status"
  | "data"
  | "module"
  | "theme";

export type IconCatalogItem = {
  name: IconName;
  category: IconCategory;
  label: string;
};

export const ICON_CATALOG: readonly IconCatalogItem[] = [
  { name: "add", category: "action", label: "Нэмэх" },
  { name: "addDocument", category: "action", label: "Баримт нэмэх" },
  { name: "approve", category: "action", label: "Батлах" },
  { name: "approveAll", category: "action", label: "Бүгдийг батлах" },
  { name: "attach", category: "action", label: "Хавсаргах" },
  { name: "cancel", category: "action", label: "Цуцлах" },
  { name: "close", category: "action", label: "Хаах" },
  { name: "copy", category: "action", label: "Хуулах" },
  { name: "delete", category: "action", label: "Устгах" },
  { name: "download", category: "action", label: "Татах" },
  { name: "duplicate", category: "action", label: "Хувилах" },
  { name: "edit", category: "action", label: "Засах" },
  { name: "filter", category: "action", label: "Шүүх" },
  { name: "maximize", category: "action", label: "Томруулах" },
  { name: "minimize", category: "action", label: "Жижигрүүлэх" },
  { name: "openExternal", category: "action", label: "Гадагш нээх" },
  { name: "openDetail", category: "action", label: "Дэлгэрэнгүй нээх" },
  { name: "power", category: "action", label: "Идэвх солих" },
  { name: "print", category: "action", label: "Хэвлэх" },
  { name: "refresh", category: "action", label: "Шинэчлэх" },
  { name: "soundOn", category: "action", label: "Дуутай" },
  { name: "soundOff", category: "action", label: "Дуугүй" },
  { name: "reset", category: "action", label: "Буцаан шинэчлэх" },
  { name: "save", category: "action", label: "Хадгалах" },
  { name: "search", category: "action", label: "Хайх" },
  { name: "send", category: "action", label: "Илгээх" },
  { name: "stop", category: "action", label: "Зогсоох" },
  { name: "undo", category: "action", label: "Буцаах" },
  { name: "upload", category: "action", label: "Оруулах" },

  { name: "arrowDown", category: "navigation", label: "Доош" },
  { name: "arrowLeft", category: "navigation", label: "Буцах" },
  { name: "arrowRight", category: "navigation", label: "Урагш" },
  { name: "arrowUp", category: "navigation", label: "Дээш" },
  { name: "chevronDown", category: "navigation", label: "Задлах" },
  { name: "chevronLeft", category: "navigation", label: "Зүүн" },
  { name: "chevronRight", category: "navigation", label: "Баруун" },
  { name: "chevronUp", category: "navigation", label: "Хураах" },
  { name: "collapseSidebar", category: "navigation", label: "Sidebar хаах" },
  { name: "expandSidebar", category: "navigation", label: "Sidebar нээх" },
  { name: "select", category: "navigation", label: "Сонголт нээх" },

  { name: "bell", category: "status", label: "Мэдэгдэл" },
  { name: "error", category: "status", label: "Алдаа" },
  { name: "help", category: "status", label: "Тусламж" },
  { name: "info", category: "status", label: "Мэдээлэл" },
  { name: "loading", category: "status", label: "Уншиж байна" },
  { name: "locked", category: "status", label: "Түгжээтэй" },
  { name: "pending", category: "status", label: "Хүлээгдэж байна" },
  { name: "success", category: "status", label: "Амжилттай" },
  { name: "unlocked", category: "status", label: "Нээлттэй" },
  { name: "warning", category: "status", label: "Анхааруулга" },

  { name: "hide", category: "data", label: "Нуух" },
  { name: "list", category: "data", label: "Жагсаалт" },
  { name: "checklist", category: "data", label: "Шалгах жагсаалт" },
  { name: "show", category: "data", label: "Харах" },
  { name: "tune", category: "data", label: "Тохируулах" },
  { name: "paste", category: "data", label: "Paste хийх" },

  { name: "ai", category: "module", label: "AI туслах" },
  { name: "bank", category: "module", label: "Банк" },
  { name: "cash", category: "module", label: "Мөнгөн хөрөнгө" },
  { name: "company", category: "module", label: "Компани" },
  { name: "costing", category: "module", label: "Өртөг" },
  { name: "counting", category: "module", label: "Тооллого" },
  { name: "dashboard", category: "module", label: "Хяналтын самбар" },
  { name: "depreciation", category: "module", label: "Элэгдэл" },
  { name: "document", category: "module", label: "Баримт" },
  { name: "file", category: "module", label: "Файл" },
  { name: "fixedAsset", category: "module", label: "Үндсэн хөрөнгө" },
  { name: "generalLedger", category: "module", label: "Ерөнхий журнал" },
  { name: "inventory", category: "module", label: "Бараа материал" },
  { name: "journal", category: "module", label: "Журнал" },
  { name: "key", category: "module", label: "Түлхүүр" },
  { name: "mail", category: "module", label: "Имэйл" },
  { name: "movement", category: "module", label: "Хөдөлгөөн" },
  { name: "packageReceipt", category: "module", label: "Бараа хүлээн авах" },
  { name: "period", category: "module", label: "Тайлант үе" },
  { name: "production", category: "module", label: "Үйлдвэрлэл" },
  {
    name: "purchaseOrder",
    category: "module",
    label: "Худалдан авалтын захиалга",
  },
  { name: "reconciliation", category: "module", label: "Тулгалт, баланс" },
  { name: "report", category: "module", label: "Тайлан" },
  { name: "reportDetailed", category: "module", label: "Дэлгэрэнгүй тайлан" },
  { name: "settings", category: "module", label: "Тохиргоо" },
  { name: "shield", category: "module", label: "Хамгаалалт" },
  { name: "spreadsheet", category: "module", label: "Хүснэгт файл" },
  { name: "theme", category: "module", label: "UI Kit" },
  { name: "trendDown", category: "module", label: "Бууралт" },
  { name: "trendUp", category: "module", label: "Өсөлт" },
  { name: "user", category: "module", label: "Хэрэглэгч" },
  { name: "warehouse", category: "module", label: "Агуулах" },

  { name: "darkMode", category: "theme", label: "Харанхуй горим" },
  { name: "lightMode", category: "theme", label: "Цайвар горим" },
  { name: "minus", category: "theme", label: "Хасах тэмдэг" },
] as const;
